---
name: AFKMine
main: kim\present\afkmine\Main
version: 0.0.1
api: [ 5.0.0 ]
author: PresentKim
description: Immersive AFK mining that a cinematic viewing experience
depend: [ CameraAPI ]

virions:
  - session-utils/1.1.0
  - selection-visualize-utils/1.2.0
  - play-sound-utils/3.0.0
  - libmultilingual/1.2.0
  - player-state-backup/1.0.0

commands:
  afkmineadmin:
    description: "Manage AFK mine"
    permission: afkmine.command.admin
    aliases: [ama]
  afkmine:
    description: "Using AFK mine"
    permission: afkmine.command.user

permissions:
  afkmine.command.admin:
    default: op
  afkmine.command.user:
    default: true
...
